site_name: Hyvä Admin Docs
site_description: Hyvä Admin Developer Documentation
copyright: Copyright &copy; Vinai Kopp 2021-present. All rights reserved.
repo_url: https://github.com/hyva-themes/magento2-hyva-admin
use_directory_urls: false
theme:
    name: material
    favicon: images/hyva-logo-192x192.png
    logo: images/hyva-logo-192x192.png
    palette:
        -   media: '(prefers-color-scheme: light)'
            scheme: default
            toggle:
                icon: material/toggle-switch-off-outline
                name: Switch to dark mode
        -   media: '(prefers-color-scheme: dark)'
            scheme: slate
            toggle:
                icon: material/toggle-switch
                name: Switch to light mode

extra:
    generator: true
    social:
        -   icon: fontawesome/brands/twitter
            link: https://twitter.com/hyva_io

markdown_extensions:
    -   pymdownx.highlight:
            anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - admonition
    - pymdownx.details
nav:
    -   'Welcome': 'index.md'
    -   '1. Guides':
            - 'guides/installation.md'
            -   'Quickstart':
                    -   'Intro': 'guides/quickstart/index.md'
                    -   'Examples':
                            - 'guides/quickstart/examples/adding-a-hyvagrid-block-in-layout-xml.md'
                            - 'guides/quickstart/examples/array-grid-provider-configuration.md'
                            - 'guides/quickstart/examples/array-grid-data-provider.md'
                            - 'guides/quickstart/examples/repository-getlist-grid-data-provider.md'
            -   'Admin Grid Walkthrough':
                    - 'guides/hyva-admin-grid-walkthrough/prerequisites-for-a-grid.md'
                    - 'guides/hyva-admin-grid-walkthrough/declaring-the-grid-block.md'
                    - 'guides/hyva-admin-grid-walkthrough/the-grid-xml-file.md'
                    - 'guides/hyva-admin-grid-walkthrough/setting-a-grid-data-source.md'
                    - 'guides/hyva-admin-grid-walkthrough/declaring-source-search-bindings.md'
                    - 'guides/hyva-admin-grid-walkthrough/using-grid-source-processors.md'
                    - 'guides/hyva-admin-grid-walkthrough/configuring-columns.md'
                    - 'guides/hyva-admin-grid-walkthrough/configuring-row-actions.md'
                    - 'guides/hyva-admin-grid-walkthrough/configuring-mass-actions.md'
                    - 'guides/hyva-admin-grid-walkthrough/pagination.md'
                    - 'guides/hyva-admin-grid-walkthrough/default-sort-order.md'
                    - 'guides/hyva-admin-grid-walkthrough/filtering.md'
                    - 'guides/hyva-admin-grid-walkthrough/buttons.md'
                    - 'guides/hyva-admin-grid-walkthrough/exports.md'
                    - 'guides/hyva-admin-grid-walkthrough/entity-config.md'
            -   'Design Docs':
                    -   'Overview': 'guides/design-docs/index.md'
                    - 'guides/design-docs/rationale.md'
                    - 'guides/design-docs/design-principles.md'
                    - 'guides/design-docs/sorting-columns.md'
                    - 'guides/design-docs/filtering-extension-attribute-columns.md'
                    - 'guides/design-docs/hyva-admin-forms-wip.md'
    -   '2. API Reference':
            -   'PHP Classes and Interfaces':
                    -   'Overview': 'api-reference/php-classes-and-interfaces/index.md'
                    - 'api-reference/php-classes-and-interfaces/hyvagridcollectionprocessorinterface.md'
                    - 'api-reference/php-classes-and-interfaces/hyvagridsourceprocessorinterface.md'
                    - 'api-reference/php-classes-and-interfaces/abstractgridsourceprocessor.md'
                    - 'api-reference/php-classes-and-interfaces/grid-abstractexporttype.md'
                    - 'api-reference/php-classes-and-interfaces/datatypeguesserinterface.md'
                    - 'api-reference/php-classes-and-interfaces/datatypeinterface.md'
                    - 'api-reference/php-classes-and-interfaces/datatypevaluetostringconverterinterface.md'
                    - 'api-reference/php-classes-and-interfaces/hyvagridarrayproviderinterface.md'
                    - 'api-reference/php-classes-and-interfaces/hyvagridfiltertypeinterface.md'
            -   'Grid XML Reference':
                    -   'Overview': 'api-reference/grid-xml-reference/index.md'
                    -   'grid > source':
                            -   'Overview': 'api-reference/grid-xml-reference/source/index.md'
                            -   'grid > source > processors':
                                    -   'Overview': 'api-reference/grid-xml-reference/source/processors/index.md'
                                    - 'api-reference/grid-xml-reference/source/processors/processor.md'
                            -   'grid > source > query':
                                    -   'Overview': 'api-reference/grid-xml-reference/source/query/index.md'
                                    - 'api-reference/grid-xml-reference/source/query/unionselect.md'
                                    -   'grid > source > query > select':
                                            -   'Overview': 'api-reference/grid-xml-reference/source/query/select/index.md'
                                            - 'api-reference/grid-xml-reference/source/query/select/groupby.md'
                                            -   'grid > source > query > select > join':
                                                    -   'Overview': 'api-reference/grid-xml-reference/source/query/select/join/index.md'
                                                    - 'api-reference/grid-xml-reference/source/query/select/join/columns.md'
                                                    - 'api-reference/grid-xml-reference/source/query/select/join/on.md'
                                            -   'grid > source > query > select > columns':
                                                    -   'Overview': 'api-reference/grid-xml-reference/source/query/select/columns/index.md'
                                                    - 'api-reference/grid-xml-reference/source/query/select/columns/expression.md'
                                                    - 'api-reference/grid-xml-reference/source/query/select/columns/column.md'
                                            - 'api-reference/grid-xml-reference/source/query/select/from.md'
                            - 'api-reference/grid-xml-reference/source/repositorylistmethod.md'
                            - 'api-reference/grid-xml-reference/source/arrayprovider.md'
                            - 'api-reference/grid-xml-reference/source/collection.md'
                            -   'grid > source > defaultSearchCriteriaBindings':
                                    -   'Overview': 'api-reference/grid-xml-reference/source/defaultsearchcriteriabindings/index.md'
                                    - 'api-reference/grid-xml-reference/source/defaultsearchcriteriabindings/field.md'
                    -   'grid > columns':
                            -   'Overview': 'api-reference/grid-xml-reference/columns/index.md'
                            -   'grid > columns > include':
                                    -   'Overview': 'api-reference/grid-xml-reference/columns/include/index.md'
                                    -   'grid > columns > include > column':
                                            -   'Overview': 'api-reference/grid-xml-reference/columns/include/column/index.md'
                                            - 'api-reference/grid-xml-reference/columns/include/column/option.md'
                            -   'grid > columns > exclude':
                                    -   'Overview': 'api-reference/grid-xml-reference/columns/exclude/index.md'
                                    - 'api-reference/grid-xml-reference/columns/exclude/column.md'
                    -   'grid > actions':
                            -   'Overview': 'api-reference/grid-xml-reference/actions/index.md'
                            -   'grid > actions > action':
                                    -   'Overview': 'api-reference/grid-xml-reference/actions/action/index.md'
                                    - 'api-reference/grid-xml-reference/actions/action/event.md'
                    -   'grid > massActions':
                            -   'Overview': 'api-reference/grid-xml-reference/massactions/index.md'
                            - 'api-reference/grid-xml-reference/massactions/action.md'
                    -   'grid > entityConfig':
                            -   'Overview': 'api-reference/grid-xml-reference/entityconfig/index.md'
                            -   'grid > entityConfig > label':
                                    -   'Overview': 'api-reference/grid-xml-reference/entityconfig/label/index.md'
                                    - 'api-reference/grid-xml-reference/entityconfig/label/plural.md'
                                    - 'api-reference/grid-xml-reference/entityconfig/label/singluar.md'
                    -   'grid > navigation':
                            -   'Overview': 'api-reference/grid-xml-reference/navigation/index.md'
                            -   'grid > navigation > exports':
                                    -   'Overview': 'api-reference/grid-xml-reference/navigation/exports/index.md'
                                    - 'api-reference/grid-xml-reference/navigation/exports/export.md'
                            -   'grid > navigation > pager':
                                    -   'Overview': 'api-reference/grid-xml-reference/navigation/pager/index.md'
                                    - 'api-reference/grid-xml-reference/navigation/pager/defaultpagesize.md'
                                    - 'api-reference/grid-xml-reference/navigation/pager/pagesizes.md'
                            -   'grid > navigation > sorting':
                                    -   'Overview': 'api-reference/grid-xml-reference/navigation/sorting/index.md'
                                    - 'api-reference/grid-xml-reference/navigation/sorting/defaultsortbycolumn.md'
                                    - 'api-reference/grid-xml-reference/navigation/sorting/defaultsortdirection.md'
                            -   'grid > navigation > filters':
                                    -   'Overview': 'api-reference/grid-xml-reference/navigation/filters/index.md'
                                    -   'grid > navigation > filters > filter':
                                            -   'Overview': 'api-reference/grid-xml-reference/navigation/filters/filter/index.md'
                                            - 'api-reference/grid-xml-reference/navigation/filters/filter/option.md'
                            -   'grid > navigation > buttons':
                                    -   'Overview': 'api-reference/grid-xml-reference/navigation/buttons/index.md'
                                    - 'api-reference/grid-xml-reference/navigation/buttons/button.md'
            -   'Event Reference':
                    -   'Overview': 'api-reference/event-reference/index.md'
                    - 'api-reference/event-reference/grid-query-before-event.md'
                    - 'api-reference/event-reference/grid-source-prefetch-events.md'
                    - 'api-reference/event-reference/grid-column-definition-build-after-event.md'
